### ISSUE TITLE
Error while installing 'Azure Static Web Apps' extension on github.dev

### ISSUE THREAD

**Issue by juliamuiruri4** [microsoft/vscode-azurestaticwebapps#924]
Steps:
1.	Create a new repository from [New repository](https://github.com/new?template_name=nextjs-hybrid-starter&template_owner=staticwebdev)
2.	Click the . button to load the project on github.dev
3.	Go to the Extensions View
4.	Search for ‘Azure Static Web Apps’ and install.

Error:
![Image](https://github.com/user-attachments/assets/26c18105-e738-4371-93b1-842ac237d492)

**Comment by alexweininger** [comment]
I **can** reproduce this, it's because it depends on Azure Resources which is not a web extension and can't be installed in github.dev. 

```
2024-12-04 10:49:18.994 [info] Getting Manifest... ms-azuretools.vscode-azurestaticwebapps
2024-12-04 10:49:18.999 [info] Installing extension: ms-azuretools.vscode-azurestaticwebapps {"isMachineScoped":false,"installPreReleaseVersion":false,"pinned":false,"installOnlyNewlyAddedFromExtensionPack":true,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/User/extensions.json","path":"/User/extensions.json","scheme":"vscode-userdata"},"productVersion":{"version":"1.96.0-insider","date":"2024-12-04T05:03:54.771Z"}}
2024-12-04 10:49:19.069 [info] Getting Manifest... ms-azuretools.vscode-azureresourcegroups
2024-12-04 10:49:19.290 [info] Installing extension: ms-azuretools.vscode-azureresourcegroups {"isMachineScoped":false,"installPreReleaseVersion":false,"pinned":false,"installOnlyNewlyAddedFromExtensionPack":true,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/User/extensions.json","path":"/User/extensions.json","scheme":"vscode-userdata"},"productVersion":{"version":"1.96.0-insider","date":"2024-12-04T05:03:54.771Z"},"context":{"dependecyOrPackExtensionInstall":true}}
2024-12-04 10:49:19.614 [error] Error while installing the extension ms-azuretools.vscode-azureresourcegroups Cannot add 'Azure Resources' because this extension is not a web extension. vscode-userdata:/User/extensions.json
2024-12-04 10:49:20.663 [info] Rollback: Uninstalled extension ms-azuretools.vscode-azurestaticwebapps
2024-12-04 10:49:20.678 [error] Error: Cannot add 'Azure Resources' because this extension is not a web extension.
    at aat.fb (https://assets.github.dev/insider/64e869f7ddf58d76097dc5ab7f36515044304b25/out/vs/workbench/workbench.web.main.internal.js:3158:43373)
    at async aat.addExtensionFromGallery (https://assets.github.dev/insider/64e869f7ddf58d76097dc5ab7f36515044304b25/out/vs/workbench/workbench.web.main.internal.js:3158:40565)
    at async H2s.h (https://assets.github.dev/insider/64e869f7ddf58d76097dc5ab7f36515044304b25/out/vs/workbench/workbench.web.main.internal.js:3158:74258)
2024-12-04 10:49:20.687 [error] Cannot add 'Azure Resources' because this extension is not a web extension.: Error: Cannot add 'Azure Resources' because this extension is not a web extension.
    at aat.fb (https://assets.github.dev/insider/64e869f7ddf58d76097dc5ab7f36515044304b25/out/vs/workbench/workbench.web.main.internal.js:3158:43373)
    at async aat.addExtensionFromGallery (https://assets.github.dev/insider/64e869f7ddf58d76097dc5ab7f36515044304b25/out/vs/workbench/workbench.web.main.internal.js:3158:40565)
    at async H2s.h (https://assets.github.dev/insider/64e869f7ddf58d76097dc5ab7f36515044304b25/out/vs/workbench/workbench.web.main.internal.js:3158:74258)
```
